export const CHANGE_USER_PARAMS = "CHANGE_USER_PARAMS"

export const FETCH_PASSENGERS = "FETCH_PASSENGERS"
export const FETCH_PASSENGERS_SUCCESS = "FETCH_PASSENGERS_SUCCESS"
export const FETCH_PASSENGERS_FAILURE = "FETCH_PASSENGERS_FAILURE"